---
title: "Modelling Emergence and Maximun Canopy"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Modelling Emergence and Maximun Canopy}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Loading libraries

```{r, warning=FALSE, message=FALSE }
library(exploreHTP)
library(dplyr)
library(kableExtra)
library(ggpubr)
library(purrr)
```

## Reading data `read_HTP()`

```{r}
data(dt_potato)
results <- read_HTP(
  data = dt_potato,
  genotype = "Gen",
  time = "DAP",
  plot = "Plot",
  traits = "Canopy",
  row = "Row",
  range = "Range"
)
```

```{r}
names(results)
```

## Data exploration

```{r, fig.width= 8, fig.height=4}
p1 <- plot(results, type = "evolution", return_gg = TRUE)
p2 <- plot(results, type = "time_by_trait", return_gg = TRUE)
ggarrange(p1, p2)
```

```{r, echo=FALSE}
kable(mutate_if(results$summ_traits, is.numeric, round, 2))
```


## Target Function 

`fn_piwise()`

\begin{equation}
f(t; t_1, t_2, k) =
\begin{cases}
0 & \text{if } t < t_1 \\
\dfrac{k}{t_2 - t_1} \cdot (t - t_1) & \text{if } t_1 \leq t \leq t_2 \\
k & \text{if } t > t_2
\end{cases}
\end{equation}


```{r, echo = FALSE, fig.width= 8}
t <- seq(0, 108, 0.1)
y_hat <- sapply(t, FUN = fn_piwise, t1 = 34.9, t2 = 61.8, k = 100)
plot(t, y_hat, type = "l")
lines(t, y_hat, col = "red")
abline(v = c(34.9, 61.8), lty = 2)
```

## Fitting Models

```{r, warning=FALSE, message=FALSE }
mod_1 <- modeler_HTP(
  x = results,
  index = "Canopy",
  plot_id = c(195, 40),
  parameters = c(t1 = 45, t2 = 80, k = 0.9),
  fn = "fn_piwise"
)
```


```{r, fig.width= 8, fig.height=4}
plot(mod_1, plot_id = c(195, 40))
kable(mod_1$param)
```

## Providing different initial values

```{r}
initials <- results |>
  pluck("dt_long") |>
  filter(trait %in% "Canopy" & plot %in% c(195, 40)) |>
  group_by(plot, genotype) |>
  summarise(k = max(value), .groups = "drop") |>
  mutate(t1 = c(40, 60), t2 = c(70, 80), .before = k)
```

```{r}
kable(initials)
```

```{r}
mod_2 <- modeler_HTP(
  x = results,
  index = "Canopy",
  plot_id = c(195, 40),
  parameters = c(t1 = 45, t2 = 80, k = 0.9),
  fn = "fn_piwise",
  initial_vals = initials
)
```

```{r, fig.width= 8, fig.height=4}
plot(mod_2, plot_id = c(195, 40))
kable(mod_2$param)
```

## Fixing some parameters of the model

```{r}
fixed_params <- results |>
  pluck("dt_long") |>
  filter(trait %in% "Canopy" & plot %in% c(195, 40)) |>
  group_by(plot, genotype) |>
  summarise(k = max(value), .groups = "drop")
```

```{r}
kable(fixed_params)
```


```{r}
mod_3 <- modeler_HTP(
  x = results,
  index = "Canopy",
  plot_id = c(195, 40),
  parameters = c(t1 = 45, t2 = 80, k = 0.9),
  fn = "fn_piwise",
  fixed_params = fixed_params
)
```

```{r, fig.width= 8, fig.height=4}
plot(mod_3, plot_id = c(195, 40))
kable(mod_3$param)
```

## Correcting Maximun value

```{r}
mod_4 <- modeler_HTP(
  x = results,
  index = "Canopy",
  plot_id = c(195, 40),
  parameters = c(t1 = 45, t2 = 80, k = 0.9),
  fn = "fn_piwise",
  fixed_params = fixed_params,
  max_as_last = TRUE
)
```

```{r, fig.width= 8, fig.height=4}
plot(mod_4, plot_id = c(195, 40))
kable(mod_4$param)
```

## Comparing Models

```{r}
rbind.data.frame(
  mutate(mod_1$param, mod = "1"),
  mutate(mod_2$param, mod = "2"),
  mutate(mod_3$param, mod = "3"),
  mutate(mod_4$param, mod = "4")
) |>
  filter(plot %in% 40) |>
  kable()
```

<hr>

## Code

```{r, eval = FALSE}
results <- read_HTP(
  data = dt_potato,
  genotype = "Gen",
  time = "DAP",
  plot = "Plot",
  traits = "Canopy",
  row = "Row",
  range = "Range"
)
fixed_params <- results$dt_long |>
  filter(trait %in% "Canopy") |>
  group_by(plot, genotype) |>
  summarise(k = max(value), .groups = "drop")
mod <- modeler_HTP(
  x = results,
  index = "Canopy",
  plot_id = NULL,
  parameters = c(t1 = 45, t2 = 80, k = 0.9),
  fn = "fn_piwise",
  fixed_params = fixed_params,
  max_as_last = TRUE
)
```
