---
title: "Modelling Maturity"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Modelling Maturity}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Loading libraries

```{r, warning=FALSE, message=FALSE }
library(flexFitR)
library(dplyr)
library(kableExtra)
library(ggpubr)
library(purrr)
```

## Exploring data `explorer()`

```{r}
data(dt_potato)
results <- explorer(dt_potato, x = DAP, y = c(Canopy, GLI_2), id = Plot)
```

```{r}
names(results)
```

## Data exploration

```{r, fig.width= 8, fig.height=6, fig.alt="plot corr"}
p1 <- plot(results, type = "evolution", return_gg = TRUE)
p2 <- plot(results, type = "x_by_var", return_gg = TRUE)
ggarrange(p1, p2, nrow = 2)
```

## Target function for maturity

`fn_lin_pl_lin()`

\begin{equation}
f(t; t_1, t_2, t_3, k, \beta) =
\begin{cases}
0 & \text{if } t < t_1 \\
\dfrac{k}{t_2 - t_1} \cdot (t - t_1) & \text{if } t_1 \leq t \leq t_2 \\
k & \text{if } t_2 \leq t \leq t_3 \\
k + \beta \cdot (t - t_3) & \text{if } t > t_3
\end{cases}
\end{equation}

```{r, echo = FALSE, fig.width= 8, fig.alt="plot fn"}
plot_fn(
  fn = "fn_lin_pl_lin",
  params = c(t1 = 38.7, t2 = 62, t3 = 90, k = 0.32, beta = -0.01),
  interval = c(0, 108),
  color = "black",
  base_size = 15
)
```

## Fitting models for maturity

```{r, warning=FALSE, message=FALSE}
mod_1 <- dt_potato |>
  modeler(
    x = DAP,
    y = GLI_2,
    grp = Plot,
    fn = "fn_lin_pl_lin",
    parameters = c(t1 = 38.7, t2 = 62, t3 = 90, k = 0.32, beta = -0.01),
    subset = c(195, 40),
    options = list(add_zero = TRUE)
  )
```


```{r, fig.width= 8, fig.height=4, fig.alt="plot fit 1"}
plot(mod_1, id = c(195, 40))
kable(mod_1$param)
```

## Fixing parameters from the canopy model

```{r}
fixed_params <- results |>
  pluck("dt_long") |>
  filter(var %in% "Canopy" & uid %in% c(195, 40)) |>
  group_by(uid) |>
  summarise(k = max(y), .groups = "drop")
```

```{r}
mod_2 <- dt_potato |>
  modeler(
    x = DAP,
    y = Canopy,
    grp = Plot,
    fn = "fn_piwise",
    parameters = c(t1 = 45, t2 = 80, k = 0.9),
    fixed_params = fixed_params,
    subset = c(195, 40),
    options = list(add_zero = TRUE, max_as_last = TRUE)
  )
```

```{r, fig.width= 8, fig.height=4, fig.alt="plot fit 2"}
plot(mod_2, id = c(195, 40))
kable(mod_2$param)
```

## Passing initial values

```{r}
initials <- mod_2 |>
  pluck("param") |>
  select(uid, t1, t2) |>
  mutate(t3 = 100, k = 0.32, beta = -0.01)
kable(initials)
```

```{r}
mod_3 <- dt_potato |>
  modeler(
    x = DAP,
    y = GLI_2,
    grp = Plot,
    fn = "fn_lin_pl_lin",
    parameters = initials,
    subset = c(195, 40),
    options = list(add_zero = TRUE)
  )
```

```{r, fig.width= 8, fig.height=4, fig.alt="plot fit 3"}
plot(mod_3, id = c(195, 40))
kable(mod_3$param)
```


## Adding constrains to the optimization

```{r}
mod_4 <- dt_potato |>
  modeler(
    x = DAP,
    y = GLI_2,
    grp = Plot,
    fn = "fn_lin_pl_lin2",
    parameters = c(t1 = 38.7, t2 = 62, dt = 28, k = 0.32, beta = -0.01),
    lower = c(-Inf, -Inf, 0, -Inf, -Inf),
    upper = c(Inf, Inf, Inf, Inf, 0),
    method = c("nlminb", "L-BFGS-B"),
    subset = c(195, 40),
    options = list(add_zero = TRUE)
  )
```

```{r, fig.width= 8, fig.height=4 , fig.alt="plot fit 4"}
plot(mod_4, id = c(195, 40))
kable(mod_4$param)
```

<hr>
